# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build:client
    - run: npm run build:server
    - name: ssh deploy build
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@191986574c0735ffad7ae1a297a414d6e6f95375
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # Remote host
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        # Remote user
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        # Source directory
        SOURCE: build/
        # Target directory
        TARGET: /root/myNode/sword-byteDance-fe/build
    - name: ssh deploy public
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@191986574c0735ffad7ae1a297a414d6e6f95375
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # Remote host
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        # Remote user
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        # Source directory
        SOURCE: public/
        # Target directory
        TARGET: /root/myNode/sword-byteDance-fe/public
    - name: ssh deploy pm2.json
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@191986574c0735ffad7ae1a297a414d6e6f95375
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # Remote host
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        # Remote user
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        # Source directory
        SOURCE: pm2.json
        # Target directory
        TARGET: /root/myNode/sword-byteDance-fe/
